import Head from 'next/head'
import LandingPageMain from '../components/LandingPage/Main'

export default function Home({ getStartedModal, setGetStartedModal}) {
  return (
    <div>
      <Head>
        <title>Go Laiv</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <LandingPageMain  getStartedModal={getStartedModal} setGetStartedModal={setGetStartedModal} />
      </main>
    </div>
  )
}
